version: '3.4'

services:
  mysite:
    image: mysite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

    env_file:
      - ../.env

    depends_on:
          - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=django_user
      - DB_PASSWORD=django_56%_pw
      - DB_NAME=invoice

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: invoice
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_56%_pw
    ports:
      - "5432:5432"

volumes:
  db_data:
