# Generated by Django 5.0.4 on 2024-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_freelancer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="contact",
            field=models.CharField(max_length=20),
        ),
    ]
