# Generated by Django 5.0.4 on 2024-05-10 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_client_name_alter_freelancer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_address",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_contact",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_email",
            field=models.CharField(
                default=None,
                max_length=100,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="freelancer_address",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="invoice",
            name="freelancer_contact",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="freelancer_email",
            field=models.CharField(
                default=None,
                max_length=100,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="freelancer_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
