# Generated by Django 5.0.4 on 2024-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0008_invoice_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="recurring",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("sent", "Sent"),
                    ("received", "Received"),
                    ("read", "Read"),
                ],
                default="Ready",
                max_length=20,
            ),
        ),
    ]
