# Generated by Django 5.0.4 on 2024-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0010_alter_invoice_total_charge_alter_invoice_total_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="services",
            field=models.TextField(null=True),
        ),
    ]
