# Generated by Django 5.0.4 on 2024-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_alter_invoice_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="been_paid",
            field=models.BooleanField(default=False),
        ),
    ]
