# Generated by Django 5.0.4 on 2024-05-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_history_been_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="invoice.client",
            ),
        ),
    ]
