# Generated by Django 5.0.4 on 2024-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_alter_invoice_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="been_paid",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
