# Generated by Django 5.0.4 on 2024-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0014_alter_history_been_paid_alter_history_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tag",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
